default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio-sid: <%= ENV['twilio_sid'] %>
  twilio-token: <%=ENV['twilio_token'] %>
  twilio_number: <%=ENV['twilio_number'] %>







development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
