development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>